blank_issues_enabled: false
contact_links:
  - name: Superlink Discord Community
    url: https://discord.com/invite/ua2rZVA8fe
    about: Ask and answer questions, share suggestions, and discuss ideas.
